### ISSUE TITLE
missing oauth/ folder?

### ISSUE THREAD

**Issue by cschalenborgh** [vasco-data-security/php-mydigipass#3]
After succesfully signing in, it redirects me to /oauth/user_data which is not included in this repo. Which files should I add?

```
Succesfully signed in using MYDIGIPASS.COM!!

The following user signed in:

Array ( [
Forbidden

You don't have permission to access /mydigipass/oauth/user_data on this server.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.
```

Some more debug

```
HTTP Request
URL	https://www.WEBSITE.com/mydigipass/oauth/token
Method	POST

RequestHeader

Array
(
)

Parameters

grant_type=authorization_code&type=web_server&client_id=CLIENT_ID&client_secret=CLIENT_SECRET&redirect_uri=https%3A%2F%2Fwww.WEBSITE.com%2Fmydigipass%2Findex.php&code=CODE_GOES_HERE

HTTP Result

URL

https://www.WEBSITE.com/mydigipass/oauth/token
Headers


Array
(
    [HTTP/1.1 403 Forbidden
] => 
    [Date] => Thu, 18 Jun 2015 10
    [Server] => Apache/2
    [Content-Length] => 421
    [Connection] => close
    [Content-Type] => text/html; charset=iso-8859-1
)


Response






Forbidden

You don't have permission to access /mydigipass/oauth/token
on this server.
```

**Comment by toonnevelsteen** [comment]
Hi Chris,

Your web app should not react to  /oauth/user_data.  That is a path
available on https://www.mydigipass.com.

The  /oauth/user_data endpoint should be consulted to retrieve data about
the user that has just been signed in.  See for more info
https://developer.mydigipass.com/secure_connect_api_reference#_user_data_endpoint

The /oauth/token endpoint is also on https://www.mydigipass.com.  I'm not
sure why your error message reports that it is on
https://www.WEBSITE.com/mydigipass.

I guess you have a configuration issue.

Toon

**Comment by cschalenborgh** [comment]
Indeed, modyfing the MDP_BASE_URI to https://www.mydigipass.com fixed it. Thanks!
